services:
  - type: web
    name: langflow-web
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir --no-deps -r requirements.txt
    startCommand: langflow run --host 0.0.0.0 --port 10000 --dev
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: free
